In [1]:
import numpy as np

In [6]:
np.c_[[1, 2, 3], [5, 6, 7]]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [8]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linalg.inv(np.array([[2, 1], [5,3]]))

array([[ 3., -1.],
       [-5.,  2.]])

In [ ]:
class LinearRegression:
    def fit(self, x, y):
        mat = np.c_[np.ones(x.shape[0]), x]
        self.weights = np.linalg.inv(mat.T @ mat) @ mat.T @ y
        return self
    

In [20]:
LinearRegression().fit(np.array([[1, 2], [3, 4], [5, 6]]), np.array([1, 2, 7])).weights

[[1. 1. 2.]
 [1. 3. 4.]
 [1. 5. 6.]]


LinAlgError: Singular matrix